// src/config/Config.h
// Lightweight configuration mapping. Credentials are injected at build time
// via src/config/credentials.h, which is auto-generated by extra_script.py
// from the project .env file. See .env.example for required variables.

#pragma once
#include <Arduino.h>
#include "config/credentials.h"

namespace Config {
    // ========================================
    // WiFi Credentials (injected from .env)
    // ========================================
    constexpr char WIFI_SSID[] = WIFI_SSID_MACRO;
    constexpr char WIFI_PASSWORD[] = WIFI_PASSWORD_MACRO;
    constexpr int WIFI_TIMEOUT_MS = 20000; // 20 seconds to connect
    constexpr uint32_t TICK_DELAY_MS           = 20;     // Main loop delay
    constexpr uint32_t WIFI_RECONNECT_INTERVAL  = 30000; // ms between reconnect attempts

    // ========================================
    // OpenWeather API Configuration (injected)
    // ========================================
    constexpr char WEATHER_API_KEY[] = OPENWEATHER_API_KEY_MACRO;
    constexpr char WEATHER_CITY[] = WEATHER_CITY_MACRO; // City,CountryCode

    // ========================================
    // OpenSky Network OAuth2 Configuration (injected)
    // ========================================
    constexpr char OPENSKY_CLIENT_ID[] = OPENSKY_CLIENT_ID_MACRO;
    constexpr char OPENSKY_CLIENT_SECRET[] = OPENSKY_CLIENT_SECRET_MACRO;
    constexpr char OPENSKY_TOKEN_ENDPOINT[] = "https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token";

    // ========================================
    // Home Location (injected from .env)
    // ========================================
    constexpr float HOME_LAT = HOME_LAT_MACRO;
    constexpr float HOME_LON = HOME_LON_MACRO;

    // Portland International Jetport (PWM) — shown as reference on radar
    constexpr float PWM_LAT = 43.6462f;
    constexpr float PWM_LON = -70.3093f;

    // ========================================
    // AeroDataBox Route Lookup
    // ========================================
    constexpr char AERODATABOX_API_KEY[] = AERODATABOX_API_KEY_MACRO;

    // ========================================
    // Radar Display
    // ========================================
    constexpr float RADAR_MAX_RANGE_NM = 25.0f;
    constexpr int16_t RADAR_CIRCLE_RADIUS = 190;   // px, circle diameter = 380

    // ========================================
    // Tracking Settings
    // ========================================
    constexpr float VISIBILITY_RANGE = 0.45f;  // ~50km radius (in degrees)
    constexpr int MAX_AIRCRAFT = 15;           // Maximum planes to track

    // ========================================
    // Update Intervals (milliseconds)
    // ========================================
    constexpr unsigned long WEATHER_UPDATE_INTERVAL = 1800000;  // 30 minutes
    constexpr unsigned long PLANE_UPDATE_INTERVAL = 30000;      // 30 seconds
    constexpr unsigned long DISPLAY_UPDATE_INTERVAL = 1000;     // 1 second
    constexpr unsigned long TOKEN_LIFETIME = 1800000;           // 30 minutes
    constexpr unsigned long PLANE_DISPLAY_TIME = 5000;          // 5 seconds per plane
    constexpr unsigned long HEALTH_UPDATE_INTERVAL = 2000;      // 2 seconds

    // ========================================
    // UI Behavior & Gestures
    // ========================================
    constexpr unsigned long UI_AUTO_HOME_MS = 60000;        // 60 seconds idle to return home
    constexpr unsigned long UI_STATUS_MS = 5000;            // 5 seconds status message
    
    // Swipe detection
    constexpr int GESTURE_SWIPE_THRESHOLD = 80;             // pixels
    constexpr int GESTURE_SWIPE_VELOCITY_MIN = 100;         // pixels/second
    constexpr unsigned long GESTURE_MAX_TIME_MS = 500;      // ms
    constexpr unsigned long GESTURE_DEBOUNCE_MS = 300;      // ms between gestures
    
    // Tap detection
    constexpr int TAP_MAX_DISTANCE = 30;                    // pixels (max travel to count as tap)
    constexpr unsigned long TAP_MAX_DURATION_MS = 200;      // ms (max duration to count as tap)

    // ========================================
    // Display & Brightness
    // ========================================
    constexpr int BRIGHTNESS_STEP = 25;
    constexpr uint8_t BRIGHTNESS_MIN = 30;
    constexpr uint8_t BRIGHTNESS_MAX = 255;
    constexpr uint8_t BRIGHTNESS_HIGH = 150;
    constexpr uint8_t BRIGHTNESS_LOW = 50;

    // ========================================
    // Time Configuration (NTP)
    // ========================================
    constexpr char NTP_SERVER[] = "pool.ntp.org";
    constexpr long GMT_OFFSET_SEC = -18000;     // Eastern Standard Time (UTC-5)
    constexpr int DAYLIGHT_OFFSET_SEC = 3600;   // +1h for DST

    // ========================================
    // Night Mode
    // ========================================
    constexpr int NIGHT_START_HOUR = 20;        // 8 PM — dim display
    constexpr int NIGHT_END_HOUR = 6;           // 6 AM — restore brightness
    constexpr uint8_t NIGHT_BRIGHTNESS = 50;    // Low brightness level

    // ========================================
    // Display Geometry
    // ========================================
    namespace Display {
        // Screen dimensions live in hal::Elecrow5Inch::PANEL_WIDTH/HEIGHT
        // Tap region: top-right corner button (aircraft detail view)
        constexpr int TAP_REGION_X_MIN = 720;
        constexpr int TAP_REGION_X_MAX = 800;
        constexpr int TAP_REGION_Y_MIN = 0;
        constexpr int TAP_REGION_Y_MAX = 80;
    }
}
